export { Login } from "./Login";
export { NoPageFound } from "./NoPageFound";
export { HomePage } from "./HomePage";
export { Register } from "./Register";
export {HomeNursingPage} from './HomeNursingPage'
export {ContactPage} from './ContactPage'
export{ LabScanPage} from './LabScanPage';
export {AmbulanceService} from './AmbulanceService'
export {Dashboard} from './Dashboard'
export {LabVendorRegistration} from './LabVendorRegistration'
export {MainDashboard} from './MainDashboard'
export {LabVendorDashboard} from './Dashboard/LabVendorDashboard'
export {UserManagementDashboard} from './Dashboard/UserManagementDashboard'
export {PackageDashboard} from './Dashboard/PackagesDashboard'
export {TestPage} from './TestPage'
export {doctorConsultation} from './DoctorConsultation'
export {surgeryPlanning} from './SurgeryPlanning'
export {Diagnostic} from './Diagnostic'
export {Physiotherapy} from './Physiotherapy'
export {Pharmacy} from './Pharmacy'
export {EditProfile} from './EditProfile'
export {MyBooking} from './MyBooking'
export {doctorRegistraion} from './DoctorRegistration'
export {doctorRegistrationDashboard} from './Dashboard/DoctorRegistrationDashboard'
export {HospitalTieups} from './HospitalTieups'
export {CorporateTieups} from './CorporateTieups'
export {SchoolTieups} from './SchoolTieups'
export {SocietyTieups} from './SocietyTieups'
export {PatientStory} from './PatientStory'
export {SurgeryPage} from './SurgeryPage'
export {AnalyticsPage} from './AnalyticsPage'
export {PrivacyPolicies} from './PrivacyPolicies'
export {RefundPage} from './RefundPage'
export {TermsAndConditionPage} from './TermsAndConditionsPage'
export {ShippingPolicyPage} from './ShippingPolicyPage'