
export default function privacy() {
    return (
        <>
            <section className="bg-gray-600 py-16 text-white ">
                <div className="container mx-auto px-4 text-center">
                    <h2 className="text-3xl md:text-4xl font-bold mb-6 ml-30">Privacy Policies</h2>
                    <p className="text-lg md:text-xl mb-8"></p>
                    {/* <a href="#" className="px-6 py-3 bg-white text-blue-600 rounded-lg font-bold shadow-md hover:bg-blue-50">
            </a> */}
                </div>
            </section>
            <div className="ml-4 md:ml-20 mr-4 md:mr-20 mt-10">

                <p className=" text-justify">This document contains terms and conditions (“Terms”) is an electronic record pursuant to the provisions of the Information Technology Act, 2000 (“IT Act”), and rules made thereunder. Further, this electronic record is generated by a computer system and does not require any physical or digital signatures. This electronic record is published in accordance with the relevant provisions of the Information Technology Act, 2000 and rules made thereunder.
                    <br />
                    <br />
                    GENERAL
                    <br />
                    <br />
                    Please note that the domain name www.mydr24.com (the “Platform”) is owned, managed and operated by Accufly Healthcare, is governed by Accufly Healthcare Pvt.Ltd, a private limited company incorporated under the provisions of the Companies Act, 2013 having its registered office at Accufly Healthcare Pvt.Ltd. Cn/29 Hauz Rani Malviya nagar south delhi 110017 Opposite Max Hospital Saket (hereinafter collectively referred to as the (Mydr24, “We”, “Us”, or “Our”).</p>
                <br />
                {/* <br/> */}
                <p className=" text-justify">For the purpose of these Terms herein above, wherever the context so requires the term “You”, “you” “Your”, “your”, or “User”, shall mean any person who visits, browses, uses or accesses the Platform or avail any Services on the Platform. and shall include (i) the persons who purport to purchase the Products on the Platform by placing an order through the Platform and (ii) the persons seeking or availing the Consultation Services (as defined below) being offered by Practitioner listed on the Platform; and (iii) the Practitioners who are registered on the Platform; (iv) the person who visits and/ or registers on the Platform.</p>
                <br />
                <p className=" text-justify">Mydr24 is a technology platform that enables and facilitates the (i) online sale and purchase of medical Equipments, pharmaceutical and nutraceutical products (“Products”) by the Users; and (ii) interaction, transaction, communication and dealing between the Practitioners and the Users who are desirous of availing the opinions, statements, answers, diagnosis, advice and e-prescription in relation to their health and wellness issues from the Practitioner by way of tele-communication, conferencing, online chat, or any other means that the Platform may provide at its discretion (“Consultation Services”). It is clarified that the term “Practitioner” shall mean any person permitted to practice medicine by the MCI (Medical Council of India) or any concerned State Medical Council as a ‘registered medical practitioner’ and who is listed on the Platform for the purpose of providing Consultation Services zto the Users.</p>
                <br />
                <br />
                <p className=" text-justify"> The facilitation of the sale and purchase of the Products and the availing and provision of the Consultation Services in accordance with the terms and conditions herein are collectively referred to as “Services”.</p>
                <br />
                <br />
                <p className=" text-justify">The Terms contained in this electronic record read with the Privacy Policy (as defined below) of Mydr24, as available and uploaded on the Platform, or any other specific terms and conditions, as applicable or relating to the sale and purchase of the Products and availing and provision Consultation Services which are incorporated herein by reference, shall constitute the entire legally and binding agreement between you and Mydr24 in connection with your access, usage, visit or use of the Platform for the purchase of Products and availing the Services, in any manner. You are requested to read these Terms carefully before accepting the same and moving forward to using and accessing the Platform or availing any Service.</p>
                <br />
                <p className=" text-justify"> In case you do not agree with these Terms, please then please refrain from using and accessing the Platform, registering on the Platform and availing any Services on the Platform.</p>

                <br />
                <p className="ml- md:ml-0 text-justify"> It is further clarified that by availing the Consultation Services and/or purchasing the Products on the Platform, and/or visiting, viewing, accessing or otherwise using any of the Services or information created, collected, compiled or submitted to the Platform, you are deemed to have agreed to these Terms and all the policies of Mydr24/ Platform.
                    <br />
                    <br />
                    It is hereby clarified that the MyDr24/ Platform may, from time to time, change provisions related to the Services which also include changing of the extent and scope of Services and/ or include any other category of service or facility within the term ‘Services’, at the sole discretion of the Platform. You can determine when these Terms were last revised by referring to ’LAST UPDATED’ at the top of these Terms. Your continued use of the Platform shall be deemed to signify Your acceptance of these provisions or amended provisions of these Terms.
                    <br />
                    <br />
                    MyDr24 reserves the right to change, modify, amend, or update the Terms, at its discretion, from time to time and such amended provisions of the Terms shall be effective immediately upon being posted/ uploaded on the Platform.
                    <br />
                    <br />
                    CREATING AN ACCOUNT
                    <br />
                    <br />
                    Please note that the Platform provides various features and in order to access and use such features, you may require to create your user account (“Account”) on the Platform and become a registered user (“Registered User”). You can have your own Account and become a Registered User on the Platform by following a signing-up process (“Sign-up”) as provided and detailed herein these Terms which includes filling up of the required information, as mentioned below in a sign-up form (“Sign-up Form”) and agreeing to the Terms as provided hereinbelow.
                    <br />
                    <br />
                    To create an Account and complete the Sign-up process, a User is required to provide the information, which such User recognizes and expressly acknowledges is personal information allowing others, including Us, to identify the User which includes name, User ID, gender, country, ZIP/postal code, age, phone number, password chosen by the User. In addition, at the time of a registered User availing of the Services, the User is required to provide certain sensitive personal information which includes its bank account or card details for undertaking transactions on the Platform for availing the Services. In addition, the information provided by the User, User’s medical history and records uploaded by the User on the Platform, medical records, logs and details of the exchanges between the Practitioner and the Users through any medium or on the Platform and the prescription issued by the Practitioner will be stored by Us for the purposes of monitoring the correctness of the order placed and for ensuring the quality of the consultation availed by a User (“Required Information”).
                    <br />
                    <br />
                    It is clarified that by Sign-up you agree to all the Terms herein, Privacy Policy and all other polices of Platform which may be posted at an appropriate location of the Platform.
                    <br />
                    <br />
                    Mydr24/ Platform shall not be liable for any loss of the Registered User caused by any unauthorized use of the Account and the Registered User, in this respect, shall indemnify Mydr24 for losses that the Mydr24 may incur from any other party on account of such unauthorized or fraudulent use of the User’s Account.
                    <br />
                    <br />
                    You agree that you shall provide accurate and correct information at the time of Sign-up for filling up of the Sing-up Form and Required Information and you shall also update such information and data, from time to time, in case of any change thereto and/ or as and when required and asked by the Platform in this regard.
                    <br />
                    <br />
                    You shall log-out from your Account at the end of each session in order to ensure complete security and secrecy of your data and mydr24’s data.
                    <br />
                    <br />
                    You are solely responsible for maintaining the confidentiality of your account, display name and password and you are fully responsible for all activities that occur under the same and Mydr24 shall not be liable or responsible whatsoever in this regard. You expressly agree that you will immediately notify us about any actual or potential unauthorized use of your account, display name and password or any breach of security or any breach of the Terms by a third party.
                    <br />
                    <br />
                    It is clarified that upon receiving a notification/ intimation/ apprehension of any actual or potential unauthorised use of any Account, your account, we may, at our discretion, take action to block access to such Account, display name and password at the earliest and take all other actions as required under the applicable laws.
                    <br />
                    <br />
                    The Registered User shall only be responsible for safeguarding the Account, password and all the information and data associated with such Account. For the safety of the data and information in such Account and prevention of any possibility of any unauthorised use thereof, it is suggested to the Registered User to use a strong password and not disclose the password to any third parties.
                    <br />
                    <br />
                    In the event of the Registered User becoming aware of any breach of security or unauthorised use of the Account, such Registered User shall take all the reasonable steps to inform Mydr24/ Platform in respect of such unauthorized use of the
                    <br />
                    <br />
                    Account and, in this regard, Mydr24/ Platform shall not be responsible for any liabilities that such Registered User may incur from the misuse of the Account or password or any data and information contained therein.
                    <br />
                    <br />
                    You agree that Mydr24 cannot and will not be liable for any loss or damage arising from your failure to comply with the Terms.
                    <br />
                    <br />
                    PRIVACY
                    <br />
                    <br />
                    You agree that during your use and access of the Platform and/or availing of the Services offered by the Platform, you will provide us with certain information and other data as mentioned under the Terms which may or may not be otherwise publicly available. Please note that we respect the privacy and confidentiality of such data and the provisions pertaining to such private information and data as provided by you under these Terms, are governed under Mydr24’s privacy policy (“Privacy Policy”) which is available at www.Mydr24.com/privacy-policy. By using and visiting the Platform and availing the Services of the Platform, you agree to the terms and conditions of our Privacy Policy.
                    <br />
                    <br />
                    Regarding your private information and data, we will only collect, use, disclose or process such information and data in accordance with our Privacy Policy, which you accept by your use and access of the Platform and/or availing the Services on the Platform. Please note that we may share such data and information with third parties as required to be shared in terms of and in the manner as set out under the Privacy Policy.
                    <br />
                    <br />
                    You agree that the measures and procedures regarding storing and securing the data and information on the Platform as stipulated in the Privacy Policy, you acknowledge, accept and agree that Mydr24 utilizes the standard security configurations for securing data and information on the Platform which is reasonable and sufficient security practice and procedure as per the industry standard and for the purposes of Information Technology Act, 2000 and the rules and regulations made thereunder.
                    <br />
                    <br />
                    By accepting these Terms, you also agree to the terms and conditions as provided under our Privacy Policy.
                    <br />
                    <br />


                    CONDITIONS TO USE PLATFORM

                    <br />
                    <br />

                    For the use and access of the Platform, whether or not for provisions of availing any of the Services on the Platform, you must be 18 (eighteen) years of age or older to use or visit the Platform, in any manner. For this purpose, you agree that by visiting the Platform or accepting these Terms, you represent and warrant to the Mydr24 that you are 18 (eighteen) years of age or older, and that you have the right, authority and capacity to use the Platform and agree to and abide by the Terms as provided herein.
                    <br />
                    <br />
                    Further, the use and access to the Platform can be availed only to such individuals who can form and enter into a valid ‘contract’ as per the conditions as provided under
                    <br />
                    <br />
                    Indian Contract Act, 1872. It is hereby expressly clarified that the persons who are ‘incompetent to contract’ within the meaning of the Indian Contract Act, 1872, including minors, un-discharged insolvents etc. are not eligible to use the Platform.
                    <br />
                    <br />
                    While individuals under the age of 18 may use or visit the Platform or avail the Services of the Platform, they shall do so only with the involvement and/ or guidance of their parents and/ or legal guardians, under such parent/legal guardian’s supervision and control. We reserve the right to deny use/ access to any to and/or exclude from our Platform, any person in our absolute discretion and we also reserve the right to suspend, revoke or amend your use/membership in our absolute discretion.
                    <br />
                    <br />
                    You agree that you will act lawfully, diligently and honestly at all times when you access and use the Platform and/or avail the Services and will comply with all laws, rules, regulations, legislations, notifications, circulars, guidelines, standards, codes, policies, orders, approvals, ordinances, judgments, decrees, injunctions, writs, arbitral award, bye-laws, or any similar form of decision, determination, or adjudication having the force of law, as amended from time to time, applicable to your use of the Platform and/or availing the Services.
                    <br />
                    <br />
                    You agree that you will not interfere with, jeopardise, disrupt or harm the Platform and/or Services and that you will not intercept, expropriate, re-use, steal or re-utilise any system, data, photographs or information comprised in or provided to you via the Platform and/or Services and at all times comply with the Terms and Mydr24’s policies.
                    <br />
                    <br />
                    We will provide you with any help you may reasonably require to access the Platform but we shall not be responsible if you are unable to access any section of the Platform or any of the Services for any reason. We do not guarantee you access to the Platform at any time and all times. We do not guarantee that while you are accessing the Platform, your access will be uninterrupted, without delay/interference, secure and/or error-free or operate as set out and anticipated in these Terms. Accordingly, we reserve the right, at any time, to suspend or discontinue the Platform and/or any of the Services for any reason without incurring any liability or obligation to you.
                    <br />
                    <br />
                    You agree that the information you provide to Mydr24 on the Platform at the time of registration and any time thereafter and any information displayed under your account at all times will be true, accurate, current, and complete. If you provide any information that is untrue, inaccurate, not current or incomplete or we have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the Terms herein and the other policies of Platform, we shall have the right to indefinitely suspend or terminate your account or block your access on the Platform.
                    <br />
                    <br />
                    If we reasonably believe that an account and password is being used / misused in any manner, we reserve the right to cancel rights to access the Platform immediately without notice, and block access to all users from that particular IP address. You agree to notify us and the Platform immediately of any unauthorized use of your account or any other breach of security. We will not be liable for any loss that you may incur as a result of someone else using your password or account. However, you could be held liable for all the losses, claims and liabilities incurred by Mydr24 due to someone else using your account or password.
                    <br />
                    <br />
                    Further, by using the Platform or sending emails, data, information or communication to the Platform through the Platform you consent to receive communications via electronic records from us periodically and as and when required.
                    <br />
                    <br />
                    The information and Services may not be used for any illegal purpose. You may not access our networks, computers, or the information and Services in any manner that could damage, disable, overburden, or impair them, or interfere with any other person’s use and enjoyment. You may not attempt to gain unauthorized access to any information or Services, other accounts, computer systems, or networks connected with the Platform, the information, or Services. You may not use any automated means (such as a scraper) to access the Platform, the information, or Services for any purpose. Such unauthorized access includes, but is not limited to, using another person’s login credentials to access his or her Account. Any attempt by any individual or entity to solicit login information of any other user or Practitioner or to access any such account is an express and direct violation of these Terms and of applicable law(s), including relevant privacy and security laws and laws prohibiting unfair or unethical business practices.
                    <br />
                    <br />
                    We may, at Our sole discretion, suspend the User’s ability to use or access the Platform at any time while we investigate complaints or alleged violations of these Terms, or for any other reason. We have the right to edit profiles of the Practitioners to make them more suitable for patient/ Users searches on the Platform.

                    <br />
                    <br />

                    CODE OF CONDUCT

                    <br />
                    <br />

                    Under these Terms, the User agrees not to host, display, upload, modify, publish, transmit, update or share any information that: (a) belongs to another person and in relation to which it does not have any right of use; (b) infringes intellectual property rights (including any patent, trademark, copyright or other proprietary rights) of any person and privacy rights of any person; (c) is false or misleading in any way; (d) violates any law for time being in force; (e) harasses or advocates harassment of another person; (f) involves the transmission of “junk mail”, “chain mail” or unsolicited mass mailing or “spamming”; (g) promotes illegal activities or abusive, obscene, defamatory or libellous conduct; (h) solicits gambling or engages in any gambling activity which is or could be construed as being illegal; (i) harms minors in any way;
                    <br />
                    <br />
                    (j) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to “indecent representation of women” within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986; (k)
                    <br />
                    <br />
                    deceives or misleads the other Users of the Platform about the origin of messages or communicates any information which is grossly offensive or menacing in nature; (l) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation; (m) promotes an illegal or unauthorized copy of another person’s copyrighted work; (n) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone; (o) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone’s privacy, or providing or creating computer viruses; (p) tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Platform or solicits passwords or personal identifying information for commercial or unlawful purposes from other users; and (q) refers to any website or URL that, in our sole discretion, contains material that is inappropriate for the Platform or any other website, application, software contains content that would be prohibited or violates the letter or spirit of these Terms;
                    <br />
                    <br />
                    The User agrees not to (a) reveal/disclose confidential or proprietary information of other Users, Mydr24/ Platform or any third party when the User receives or comes in possession of such confidential or proprietary information; (b) incorporate any computer contaminant, software virus or any computer code or file or program on the Platform designed to interrupt, destroy or limit the functionality of the Platform; (c) incorporate or introduce any program on the Platform that might infringe the intellectual property rights of any other User and/or of Mydr24/ Platform; (d) download, copy, reproduce any file or information available on the Platform which the User knows, or reasonably should know, cannot be legally reproduced, displayed, performed, and/or distributed; (e) in any way, deface or vandalize the Platform or prevent or restrict others from using the Platform; (f) stalks, threaten or harass any other User or infringe upon or attempt to infringe upon their privacy; (g) infringe any patent, trademark, copyright or other proprietary rights or third party’s trade secrets or rights of publicity or privacy, of Mydr24/ Platform, other Users of the Platform or any third Party; (h) impersonate any person or entity, or falsely state or otherwise misrepresent themselves or their affiliation with any person or entity; (i) directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force; and (j) create liability for Mydr24/ Platform or cause Mydr24/ Platform to lose (in whole or in part) the services of its internet service provider or other suppliers.
                    <br />
                    <br />
                    It is also clarified that you shall not use any “deep-link”, “page-scrape”, “robot”, “spider” or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Platform or any product/service, or in any way reproduce or circumvent the navigational structure or presentation of the Platform or any product/service, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Platform. We reserve the right to bar any such activity.
                    <br />
                    <br />
                    You agree that you shall not attempt to gain unauthorized access to any portion or feature of the Platform or any feature pertaining to availing of Services or any other systems or networks connected to the Platform or to any server, computer, network, or to any of the product/services offered on or through the Platform, by hacking, password “mining” or any other illegitimate mean.
                    <br />
                    <br />
                    You agree that you shall not probe, scan or test the vulnerability of the Platform or any network connected to the Platform nor breach the security or authentication measures on the Platform or any network connected to the Platform. You may not reverse look-up, trace or seek to trace any information on any other User of or visitor to Platform, or any other client/customer/user/member of Mydr24/ Platform including any account on the Platform not owned/operated/managed by you, to its source, or exploit the Platform or any product/service or information made available or offered by or through the Platform, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than your own information, as provided for by the Platform.
                    <br />
                    <br />
                    You agree that you shall not make any negative, denigrating or defamatory statement and/or comment about the Platform/ Mydr24 or the Practitioner or purchase of Products or the brand name or domain name used by Mydr24/ Platform or otherwise engage in any conduct or action that might tarnish the image or reputation of the Platform/ Mydr24, the Practitioner or other Users on the Platform or other business partners of Mydr24 or otherwise tarnish or dilute any of Mydr24’s trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by the Platform.
                    <br />
                    <br />
                    You agree that you will not use the Platform or any content thereof for any purpose which is unlawful or prohibited by the Terms or to solicit the performance of any illegal activity or other activity which infringes the rights of Mydr24/ Platform, its Users and/or others third parties.
                    <br />
                    <br />
                    You agree that you shall, at all times, ensure full compliance with the applicable provisions of the Information Technology Act, 2000, and the rules thereunder as applicable and as amended from time to time and, also all applicable laws, rules and regulations and international laws, statutes, ordinances and regulations regarding use of the Products and/ or availing of the Consultation Services and the transactions between you and other Users. Further, you agree that you shall not solicit (directly or indirectly) any other Users of the Platform to avail the Services of the Platform being displayed on the Platform, either independently or through a third party except through the Mydr24/ Platform.
                    <br />
                    <br />
                    The User shall indemnify and hold harmless the Mydr24, its owners, licensees, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from all losses, claims, damages, penalties, costs,
                    <br />
                    <br />
                    expenses, demands, actions (including reasonable attorneys’ fees) suffered or incurred by the Platform due to or arising out of breach of these Terms and other policies of Mydr24/ Platform.
                    <br />
                    <br />
                    To enable use of your information supplied by you to us, so that use of any such information by us is not construed as a violation of any rights, you agree to grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights you have in your information, in any media now known or not currently known, with respect to your information. We will only use your information in accordance with the Terms and the polices of Mydr24/ Platform applicable to the use of the Platform.

                    <br />
                    <br />

                    CONSULTATION SERVICES
                    <br />
                    <br />


                    In order to avail the Consultation Services, the User is required to have an Account and become a Registered User. It is hereby clarified that the Registered User must opt for consultation/session through the Platform by way of tele-communication, conferencing, online chat, or any other means that the Mydr24/ Platform may provide at its discretion. Upon the User opting for any medium for consultation/ session, the User will be automatically assigned to a Practitioner through Mydr24’s system algorithm/ software-program that finds the most available, accepting and/ or geographically accessible Practitioner. The Practitioner’s acceptance of the User’s offer to avail the services and consultation by the User, is completely at the discretion of the Practitioner.
                    <br />
                    <br />
                    For the purpose of Consultation Services, the User will be asked to fill the Required Information at the time of Sign-up and certain other information which the Platform may require the User to provide before initiating the consultation session with the Practitioner which includes, inter alia, particulars pertaining to prescription and medical history of the User. The User agrees to provide all such information on the Platform as and when prompted and required by the Platform.
                    <br />
                    <br />
                    It is clarified that pursuant to such consultation session between the Practitioner and the User, the Practitioner may prescribe certain products to be administered by the User.
                    <br />
                    <br />
                    It is hereby clarified that for the purpose of facilitation of interaction, communication, dealing, consultation, advice and transaction between the Practitioner and the User is an independent and separate transaction between such Practitioner and User and Platform is only acting as an intermediary service provider for the purpose of facilitation of interaction, communication, dealing, consultation, advice and transaction between the Practitioner and the User; and hence, Mydr24 shall not be liable and responsible for any and all liabilities, losses, claims and damages that may arise out of or in connection with the interaction, dealings, consultation, communication and transaction between the Practitioner and the User and the User agrees to hold harmless and indemnify Mydr24 in this regard.
                    <br />
                    <br />
                    The User understands that prior to availing the Consultation Services on the Platform, the User will be required to a pay a consultation fee for booking a single consultation session to be provided by the Practitioner on the Platform (“Consultation Fee”).
                    <br />
                    <br />
                    It is clarified that for every booking of consultation session by the User on the Platform, the User shall not obtain Consultation Service for more than one person and, in the event, the User attempts to obtain Consultation Service for more than one User through a single paid Consultation Fee, such Consultation Service will not be addressed by the Practitioner and in this respect Mydr24/ Platform shall have the right to cancel such Consultation Service for the User and suspend the User’s Account.
                    <br />
                    <br />
                    The User understands and agrees that (i) the Consultation Service which is provided on the Platform, may vary from a consultation where the User is examined in person, and therefore agrees that any prescription provided by the Practitioner shall not be relied upon as final and/or conclusive by the User; (ii) the advice provided by the Practitioner is based on general medical conditions and practices prevalent in India and not for the conditions which are specific to the User’s or Practitioner’s territory, irrespective of where the User is procuring services of the Practitioner through the Platform; (iii) consultation with the Practitioner shall not substitute treatment that needs physical examination; (iv) in case the User pays the Consultation fee in order to avail the Consultation Service and engages in communication and exchange of money for services from such Practitioner outside of the Platform, the User shall do so at their own risk and Mydr24/ Platform shall not be responsible for any breach of service or service deficiency by any Practitioner; (v) any communication that the User has with the Practitioner through the Platform, and via telephone, text and email, before or after the Consultation Service, will be subject to doctor-patient confidentiality and treated as such as per the applicable laws, and Mydr24/ Platform shall not be liable for any communication, or the timelines of communication, between the User and the Practitioner; and (vi) the User shall not use abusive or inappropriate language while communicating with the Practitioner and in the event any User is reported by the Practitioner for using abusive or inappropriate language, the Mydr24/ Platform reserves the right to suspend or terminate the User’s Account, and in this regard Mydr24/ Platform will not be liable to honour any refund request towards the Consultation Fee paid by the User on the Platform.
                    <br />
                    <br />
                    The User shall indemnify and hold harmless the Mydr24/ Platform and its affiliates, subsidiaries, directors, officers, employees and agents from and against any and all claims, proceedings, penalties, damages, loss, liability, actions, costs and expenses (including but not limited to court fees and attorney fees) arising due to or in relation to the use of Platform by the User, by breach of the Terms and Conditions or any claim of the User arising out of interaction, communication, dealing, consultation, advice and transaction (included but not limited any advice/ statement/ service provided by the Practitioner and issuance of the prescription by the Practitioner to the User) between the User and the Practitioner.
                    <br />
                    <br />
                    You acknowledge that the Practitioners empanelled with us are independent contractors and we have an independent contractor relationship with such Practitioner and, therefore, in no event we will be directly or vicariously liable for any advice or medical consultancy or any loss arising therefrom that the Practitioner may provide to You or You may avail as part of the Consultation Services.
                    <br />
                    <br />
                    The Consultation Service are not to be used in medical emergencies or for critical health situations requiring prompt medical attention. The Consultation Service is not intended to be real-time and may not be the best solution when a face-to-face consultation is a must and, therefore, We strongly discourage any delay in seeking advice from Your doctor on account of something that You may have heard/viewed on the Platform. You take full responsibility for ensuring that the information submitted is accurate and we shall not make any effort to validate any information provided by You for using the Services with respect to content, correctness or usability. We, with an intention to provide the best services possible, could ask You to share more information as and when needed.
                    <br />
                    <br />
                    The opinions, statements, answers and tele-consultations provided by the Practitioner through the Platform are solely the individual and independent opinions and statements of such Practitioners and do not reflect the opinions of Platform, its affiliates or any other organizations or institutions to which such Practitioner or such specialist or professional is affiliated or provides services. Mydr24/Platform does not recommend or endorse any specific tests, physicians, products, procedures, opinions, or other information that may be mentioned on the Platform or by a licensee of Platform.
                    <br />
                    <br />
                    The inclusion of professionals, specialists and/ or the Practitioners on the Website or in any professional directory on the Platform does not imply recommendation or endorsement of such specialists and/ or Practitioner nor is such information intended as a tool for verifying the credentials, qualifications, or abilities of any specialists and/ or Practitioners contained therein. Such information is provided on an ‘as-is’ basis and Mydr24/ Platform disclaims all warranties, either express or implied, including but not limited to the implied warranties of merchantability and fitness for particular purpose.
                    <br />
                    <br />
                    Mydr24/ Platform, the Practitioner and third-party professionals who offer the services through the Platform accept no responsibility for any medical, legal or financial events or outcomes related to such services availed through the use of the Platform.
                    <br />
                    <br />
                    We make no warranty that the Consultation Service will meet Your requirements, or that the Consultation Service will be uninterrupted, timely, secure, or error-free. This includes loss of data or any service interruption caused by Platform’s employees. We are not responsible for transmission errors, corruption of data.
                    <br />
                    <br />
                    The Platform is for personal use and the Consultation Service are for individuals to use for supporting their personal health decisions. You may use the Platform for personal, but not for commercial, purposes.
                    <br />
                    <br />
                    While the Platform is an honest attempt to provide access to the best possible medical information to the Users by the Practitioner, the Practitioner will not be examining You physically. The Practitioner may not have access to all or some of Your medical history that might be critical to consult You. The Practitioner will not have the benefit of information that would be obtained by examining You in person, observing Your physical condition and by going through Your medical records. This means that the Consultation Services provided is different from the diagnostic and treatment services typically decided by a physician. Therefore, the Practitioner may not be aware of facts or information that would affect his or her opinion of Your diagnosis. To reduce the risk of this limitation, we strongly encourage You to be in touch with an on-ground physician and share our opinion with him/her.
                    <br />
                    <br />
                    The Consultation Service is not intended to replace a face-to-face visit with a physician and it does not replace an actual doctor-patient relationship; in case of a second opinion where there is a difference of opinion among the Practitioner and Your physician, You would bear the responsibility to decide on online or offline consultation, or procedure, and/or treatment; in rare cases, the Practitioners may feel that the query may not be answerable without physically examining the Users and the Consultation Service may be refused forthwith.
                    <br />
                    <br />
                    The Practitioners are independent professionals solely responsible for the Consultation Service to be availed by you. Mydr24/ Platform does not practice medicine and does not interfere with the practice of medicine and the Practitioner is responsible for his or her services and compliance with the requirements applicable to his or her profession.
                    <br />
                    <br />
                    In respect of your interaction, dealing, transaction and communication with the Practitioner for Consultation Service, please note that we do not have any control over such information and play no determinative role in the finalization of the same and hence do not stand liable for the outcomes of such interaction, dealing, transaction and communication. Your interaction, dealing, transaction and communication with the Practitioner forms a separate bi-partite arrange between them and thus, any claim arising from such breach is the subject matter of the Practitioner and you alone and we are in no way a party to such breach or involved in any suit claim/negligence/damages etc arising from the same breach.
                    <br />
                    <br />
                    We are in no way liable for any deficiency of services if any arises including but not limited to cancellation of order due to any unavailability of the Practitioner. We are not liable for the general conduct of the Practitioner and we shall not be liable for any unwarranted act performed by the Practitioners. You are advised to ensure your safety and the safety of your belongings.
                    <br />
                    <br />
                    It is clarified that the Platform shall not be held liable neither to the Practitioners nor the Users for any offer of service/consultation/ communication made between them for whatsoever reason it may be. Further the Platform shall not be held liable by Users for any technical mishap of whatever kind. The Platform is only an intermediary and cannot be held liable for any dispute/claim/damages etc that arise between the Practitioners and the Users for whatsoever reason it may be and the User indemnify and hold harmless the Mydr24 for any claims arising out or in relation to the same.
                    <br />
                    <br />


                    PURCHASE OF PRODUCTS AND PRESCRIPTION POLICY
                    <br />
                    <br />


                    The Platform provides and lists a variety of Products which the User can purchase. Such Products include pharmaceutical and nutraceutical products. In order to purchase Products on the Platform, the User is required to have an Account and become a Registered User.
                    <br />
                    <br />
                    The User agrees that for the purchase of Products, for which a prescription by a registered medical practitioner registered with Medical Council of India and/ or concerned State Medical Council under the provisions of Indian Medical Council Act, 1956 (“RMP”) is mandatory, then such Products shall only be dispensed on the submission of a valid prescription from such RMP by uploading the prescription of the Platform or in the manner as provided on the Platform.
                    <br />
                    <br />
                    The User can place an order for purchase of Products on the Platform from the Account for which certain information may be required from the User. The User agree that the User shall provide all such information and data, including health summary and medical history whenever and in whatsoever manner asked by Mydr24/ Platform. In this respect, the Registered User confirms that the User shall accurately disclose the personal health information and provide the required consent to use such personal health information by Mydr24/ Platform for the purpose of sale of any Product to such User.
                    <br />
                    <br />
                    The User further acknowledges that uploading of the prescription provided by the Practitioner will be mandatory in case any Product is required to dispensed only by a prescription from an RMP. In such case, the you will send us or upload a scanned copy of your valid prescription(s) in the manner as provided on the Platform and such prescription shall be subject to the scrutiny of and approval by our qualified personnel in this respect.
                    <br />
                    <br />
                    Pursuant to placing of such purchase order, Mydr24 might contact the User via telephone call or any other mode of communication in order to confirm the validation/verification of the prescription provided by the User in case of purchase of Products requiring prescription by an RMP and/ or in respect of any other required and necessary information for the sale and dispatch of such Product. In case, our qualified personnel have any queries or concerns about your prescriptions issued by
                    <br />
                    <br />
                    Practitioner/ RMP, you hereby authorize our qualified personnel them to consult with an external network of doctors about the validity of the prescription.
                    <br />
                    <br />
                    It is hereby clarified that Mydr24/ Platform shall not be liable for any claim/ liability arising out of or in connection with the illegal/ unauthorized/ invalid prescription which has been uploaded by the User for purchasing the Products on the Platform.
                    <br />
                    <br />
                    Please note that you will be required to upload a scanned copy of the valid prescription on the Platform for the purchase of prescription Products. The order for the purchase of prescription Products would not be processed by us until we receive a copy of a valid prescription. Representative of Mydr24/ Platform will verify the prescription forwarded by You and in case our representative observes any discrepancy in the prescription uploaded by You, we will cancel your order for the purchase of Products immediately. When the prescription Products are ordered, You are also required to make the original prescription available at the time of receipt of delivery of such Products. Further, You shall allow the delivery agent to stamp the original prescription at the time of delivery of Products, failing which the prescription Products will not be delivered.
                    <br />
                    <br />
                    You acknowledge and accept that the order for a substitute of a prescription Product would only be processed by us if the RMP has himself/ herself permitted for any other equivalent generic drug to be dispensed in place of the prescription Product in the prescription receipt or if the prescription solely lists the salt names or upon confirmation or verification from an RMP instead of a specific brand name or upon confirmation or verification from the Practitioner and You further acknowledge and accept that, in the absence of the above, we will dispense a substitute Product in place of the prescription Product.
                    <br />
                    <br />
                    The Registered User agrees and acknowledges that the property and title in the Products ordered and purchased through Platform shall be transferred upon the dispensation of the Products and raising of the invoice of sale by Mydr24/ Platform in this respect.
                    <br />
                    <br />
                    In respect of Purchase of Products from Platform, it be noted that (i) the User acknowledges that listing of the Products on the Platform for sale is merely an invitation to an offer for sale and not an offer for sale and placement of a purchase order on the Platform shall only constitute an offer by the User to enter into an agreement with the Mydr24/ Platform subject to the provisions of these Terms; (ii) Mydr24 may accept or decline any order placed by the User; and (iii) the Mydr24/ Platform reserves the right to discontinue from sale any Product without any prior notice to you or third party.
                    <br />
                    <br />
                    The Registered User hereby authorise Mydr24/ Platform to ship the purchase order by post/ courier to the designated location as indicated in the purchase order.
                    <br />
                    <br />
                    It is clarified that it is imperative to seek professional advice from your physician before purchasing or consuming any medicine from Platform.

                    <br />
                    <br />

                    FEEDBACK AND PRODUCT REVIEW

                    <br />
                    <br />

                    In respect of the Consultation Services, the Registered Users who avail the services of the Practitioners, are allowed to provide feedback, ratings, reviews and particulars about the experiences in respect of the such consultation with the Practitioner (“Feedback”), which the Mydr24/ Platform may or may not publish at their sole discretion, however, the User shall ensure that providing such feedback and/or consultation experience does not violate any applicable law and must not infringe on third-party intellectual property rights or privacy rights.
                    <br />
                    <br />
                    In this respect, it is clarified that the User shall be solely responsible for the content of the Feedback such Users have provided on the Platform and, if such Feedback is published, the role of Mydr24/ Platform in publishing of such Feedback shall of an ‘intermediary’ under the provisions of the Information Technology act 2000 and, therefore, Mydr24 here disclaims all liability with respect to the content of the Feedback and it is clarified that Mydr24/ Platform does not endorse any opinions or experiences contained within the content of such Feedback.
                    <br />
                    <br />
                    In respect of the Purchase of the Products on the Platform, the Registered Users are allowed to provide feedback, ratings, reviews and particulars about the experiences in respect of the such Purchase of the Products (“Product Review”), which Mydr24/ Platform may or may not publish at their sole discretion, however, the User shall ensure that the providing of such Product Review does not violate any applicable law and must not infringe on third-party intellectual property rights or privacy rights.
                    <br />
                    <br />
                    The User shall ensure that submission of Product Review and/ or Feedback shall not be offensive on moral, religious, racial or political grounds or of an abusive, indecent, threatening, unlawful, obscene, defamatory, menacing or otherwise objectionable nature.
                    <br />
                    <br />


                    USER’S CONTENT

                    <br />
                    <br />

                    It is hereby clarified that the content that you upload or post will become our property and you grant us the worldwide, perpetual and transferable rights in such content, including but not limited to Feedback and Product Review. We shall be entitled to, consistent with our Privacy Policy as adopted in accordance with applicable law, use the content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include any content you provide and are not entitled to any payment or other compensation for such use. You also grant us the right to sub-license these rights, and the right to bring an action for infringement of these rights. We reserve the right to edit or remove any material submitted to the Platform, or stored on our servers, or hosted or published upon the Platform.
                    <br />
                    <br />
                    Posting any form of content by the User on the Platform must verify the truthfulness and authenticity of the particulars of the content, including the time, place and nature. Before allowing such content to be posted on the Platform, we have the right and authority to verify the accuracy of such particulars related to the content with the respective sources provided by the user posting such content, if we feel that there is a need to check such accuracy. We have the right to upload content on behalf of third parties, subsequent to collecting such information and verifying it if we deem it necessary. Notwithstanding this, we can in no way be held liable for any false or misleading information.
                    <br />
                    <br />
                    In case any content is considered to be unlawful or against the law within any jurisdiction in which the Platform can be seen and accessed, it shall be removed forthwith by us on being intimated by the authorities of the respective jurisdiction that such content is deemed unlawful. We cannot be held liable or questioned for the same.

                    <br />
                    <br />

                    PAYMENT TERMS

                    <br />
                    <br />

                    Please note that some of the Services on the Platform are chargeable as may be specified from time to time. We will inform you about the applicable charges for any paid Service and the related payment terms presented to you. You can add the desired Services to your order cart which will indicate the applicable charges in respect of such Services added to the order cart.
                    <br />
                    <br />
                    However, it be noted that in respect of the Consultation Service, you will be required to make payment only when you actually avail such Consultation Service; and, in respect of the purchase of Products, first verification of the order placed by you for purchase of the Products shall be done by Platform’s representative, including the case where a prescription is uploaded on the Platform by the User/ provided by the User to the Platform for purchase of the Products.
                    <br />
                    <br />
                    For the purpose of making payments towards Consultation Fee/ purchase amount for the product post verification by the representative of Mydr24/ Platform, the User can make such payments via any one of the following methods of payment:
                    <br />
                    <br />
                    Credit/Debit Card;

                    Net Banking;

                    Cash on Delivery, if applicable for the relevant purchase; or
                    <br />
                    <br />
                    Please note that in the event of any loss or damage arising directly or indirectly to the User on account of lack of authorization for any transaction or any other issue whatsoever arising in respect of the transaction and/or the decline of the transaction for any reason whatsoever.
                    <br />
                    <br />
                    It is clarified that Product Fee shall consist of delivery charges which shall by determined and charged on the purchase order in the following manner:

                    Rs. 50 or free delivery
                    <br />
                    <br />
                    It is agreed between the Parties that all payments made against the services on the Platform shall be in INR and the Platform shall not facilitate transaction with respect to any other form of currency for the payment to be made to avail the Services.
                    <br />
                    <br />
                    Any payment in respect of Services shall be subject to applicable tax laws of India.
                    <br />
                    <br />
                    The User may cancel a purchase order for Products within 24 hours of uploading the prescription on the Platform. Please note that once we ship the Product, you can cancel the purchase order by incurring INR 80 as delivery expenses. In order to cancel your purchase order for Products, please contact us on WhatsApp at93117 91119 (“WhatsApp Customer Support”).
                    <br />
                    <br />
                    For the Consultation Service, the User can cancel such scheduling of consultation session by denying your availability for such consultation session to our customer care executive who will contact you before your scheduled consultation session.
                    <br />
                    <br />
                    If an appointment is cancelled due to the abusive nature of the User, such User shall not be entitled for any refunds, and Mydr24 and/ or Practitioner shall be entitled to take any legal action, depending upon the gravity of the matter.
                    <br />
                    <br />
                    In case a Practitioner does not respond to a paid consultation within ten (10) minutes from the time of starting a consultation on the Platform, or does not respond for more than fifteen (15) minutes during an active consultation session, the User shall have the right to request for a refunds, and any amounts paid by the User with respect to the Consultation Fee. [BL1]
                    <br />
                    <br />
                    In respect of purchase of the Products, we do our best to ensure that the Products you ordered are delivered as per the particulars you have provided. In the event, if you receive an incomplete order, damaged or incorrect Product(s), you are requested to notify the Customer Support (as defined below) immediately or within 7 working days of receiving of such Products so that we can ensure prompt resolution. Please note that we will only allow the return and refund of unopened and unused Products in the same condition as at the delivery. Please note that we will not accept any liability for any issues if you fail to notify us within 7 working days of receipt of the Product.
                    <br />
                    <br />
                    We also understand that various circumstances may arise leading you to want to return Product(s) which are not defective, damaged and/ or incomplete. In such cases, we may allow the return of unopened and unused products after deducting a 20% restocking charge, ONLY if you notify us within 30 working days of receipt of the Product(s).
                    <br />
                    <br />
                    We will issue a full refund for the Products in case the User received a defective Product, the Product is lost or damaged during transit and/ or the ordered Product(s) are past expiry date.
                    <br />
                    <br />
                    Please note that Mydr24/ Platform reserves the right to refuse returns (or refunds) for certain products, as marked in the respective product pages as “Note: This item cannot be returned for a refund or exchange.”
                    <br />
                    <br />
                    Mode of refund may vary depending on circumstances. If the mode of refund is by Credit/Debit Card or Net Banking, please note that it may take 7 to 10 working days for the credit to appear in your account. While we regret any inconvenience caused by this time frame, it be noted that it is the bank’s policy that delays the refund timing and we have no control over the same.
                    <br />
                    <br />
                    In order to request a refund, you need to contact us on WhatsApp Customer Support with your order details, including the reason why you’re requesting a refund. Please note that we take customer feedback very seriously and use it to constantly improve our quality of service.
                    <br />
                    <br />
                    If You have any queries in relation to any issue, you can call our help desk at 9326143233 or email us at care@Mydr24.in [insert email] or contact our customer support executives through online chat on the Platform (“Customer Support”).
                    <br />
                    <br />


                    THIRD PARTY ADVERTISEMENTS
                    <br />
                    <br />


                    As part of the Services provided by Us; We facilitate and allow third party advertisers (“Third Party Advertisers”) to place advertisements on the Platform in accordance with our advertisement policy.
                    <br />
                    <br />
                    We clearly distinguish between the editorial content and content that is created or provided by one of our Third Party Advertisers. The advertisements will be labelled as “sponsored”, “from our Advertisers” or “advertisement”. This content will not be reviewed by Our in-house editorial staff and shall be subject to the Advertising Policy, these Terms and the Privacy Policy.
                    <br />
                    <br />
                    Please note that We do not verify any content or information provided by the Third Party Advertisers on the Platform and to the fullest extent permitted by applicable law(s), disclaim all liability arising out of Third Party Advertisers’ use or reliance upon the Platform, availing the Services, content posted by Third Party Advertisers, representations and warranties made by the Third Party Advertisers on the Platform or any loss arising out of the manner in which the Services have been availed by the Users.
                    <br />
                    <br />
                    The Platform may be linked to the website of third parties, affiliates and business partners. By clicking on the advertisements by Third Party Advertisers, the User may be redirected to a website or other electronic platform of any Third Party Advertisers or receive other messages, information or offers from such Third Party Advertisers. We have no control over, and not liable or responsible for content, accuracy, validity, reliability, quality of such websites or made available by/through the Platform. Inclusion of any link on the Platform does not imply that we endorse the linked website. The User is wholly liable for all communications and transactions with advertisers. The User acknowledges and agrees that the Mydr24/ Platform is
                    <br />
                    <br />
                    not liable or responsible for the content, products or services of such advertisers or the websites, links, information, messages, offers or privacy practices of such advertisers
                    <br />
                    <br />
                    Users accept and acknowledge that we do not provide any representation or give any guarantee or warranty (whether express or implied, or whether arising by virtue of a statute or otherwise in law or from a course of dealing or usage or trade) in relation to the goods/ products and services made available on the Platform by Third Party Advertisers, including any guarantee or warranty that such goods/ products (i) are merchantable; (ii) fit for the purpose of which they are to be (or have been) purchased;(iii) have accurate description; and (iv) do not cause any infringement.
                    <br />
                    <br />
                    The User acknowledges and agrees that Mydr24/ Platform is not responsible for the availability of Third Party Advertisers’ links, content, websites, products or services and will not be responsible or liable for any content, advertising, products or other materials contained therein or the business practices or privacy practices related thereto. The User warrants and agrees that the Mydr24 will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such link, website, content, product and/or service.
                    <br />
                    <br />
                    The content on the Platform which includes all text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, design documents, and artwork is Our content and the Platform may contain links to/ content of third party websites that are not associated with us. We have no control over any third party user generated content as we are merely an intermediary for the purposes of those content. In the event, if any of the third party content infringes any intellectual property of any person, such third party shall be solely responsible for any loss caused and we shall not be liable.


                    <br />
                    <br />

                    INDEMNITY

                    <br />
                    <br />

                    In addition and not in derogation of the specific indemnities provided by you to Mydr24/ Platform under these Terms and/or policies of Mydr24/ Platform, you agree to indemnify, defend and hold harmless the Mydr24 and its affiliates, officers, directors, employees, consultants, representatives, shareholders, contractors, users and agents etc. against any and any and all losses, liabilities, claims, damages, demands, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) arising out of or in connection with any claim, suit, action, or other proceeding brought against Mydr24/ Platform or such party, to the extent such Losses are based on or arising out of or in connection with:
                    <br />
                    <br />
                    any breach or non-performance of any of the Terms and/ or other terms and conditions of Mydr24/ Platform with respect to use and access of the Platform, Consultation Service and/ or purchase of the Product; (b) truthfulness and correctness of the information provided by the User at the time of Sign-up and/ or availing the Services including purchase of the Products and availing consultation Service from the Practitioner; (c) any claim which the Practitioner may have with
                    <br />
                    <br />
                    respect to interaction, communication, dealing, consultation, advice and transaction between the Practitioner and the User; (d) any content posted by the User on the Platform and User’s use of the Services available on the Platform; (e) any third party due to, or arising out of, or in connection with, your use of the Platform and/ or availing of Services; (f) breach of any third party rights (including, but not limited to, claims in respect of defamation, invasion of privacy, or infringement of any other intellectual property right) by you.
                    <br />
                    <br />


                    INTELLECTUAL PROPERTY RIGHTS
                    <br />
                    <br />


                    For the purpose of these Terms herein, the terms, “IPRs” or “Intellectual Property Rights” shall mean on a worldwide basis, all patents, copyrights, trade secrets, service marks, trademarks, trade names, trade dress, trademark applications and registrations, internet domain names, design rights, and all other proprietary and intellectual property rights as may exist now and hereafter come into existence, and all renewals and extensions thereof, regardless of whether any of such rights arise under any applicable law.
                    <br />
                    <br />
                    It is further acknowledged and agreed by you that all the IPRs in all material presented on the Platform, including but not limited to text, audio, video or graphical images, interfaces, graphics, design, compilation, information, computer code, products, software, downloadable software, trademarks, logos and all other material appearing on the Platform are the property of Mydr24, its parent, affiliates and associates and are protected under applicable Indian laws.
                    <br />
                    <br />
                    It is hereby clarified and agreed by you that (i) Mydr24/ Platform own all the intellectual property rights in and relating to Mydr24/ Platform, Products and Services offered through Platform and your use of the Platform and/or availing of Services does not grant or confer you any rights in relation to our IPRs or our affiliates or licensor’s or suppliers’ IPRs; (ii) the structure of the Platform shall not be reproduced, distributed or published, in whole or in part, by you for any purpose; other than in connection with your private use of the Platform and/ or availing of Services, you shall not copy, reproduce, download, publish, adapt, create derivative works, re-publish, post, broadcast, record, print, commercially exploit, transmit, edit, communicate to the public or distribute in any other way, any IPRs or content in relation to the Platform and/ or availing of the Services or the computer codes or elements which comprise the Platform; (iii) by using, accessing or visiting the Platform and/ or availing the Services, you acknowledge and agree that the general layout, content and design of the Platform is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws and these Terms does not grant to you any rights to any IPRs in respect of the Platform or any content; (iv) the User cannot create any derivative work or technology based upon any IPRs, confidential or proprietary information of Mydr24/ Platform; (v)the User cannot adapt or use any trademark, service mark, trade name, logo or domain name similar to or likely to be confused with those of Mydr24/ Platform or take any other action that infringes upon or impairs Mydr24’s trademark (whether registered or unregistered) or other IPRs; and (vi) other than as set out in this clause and the
                    <br />
                    <br />
                    Platform’s policies, you are not permitted to use any of our intellectual property rights without our (and our affiliates, licensor’s or suppliers) prior written consent.
                    <br />
                    <br />


                    TERMINATION
                    <br />
                    <br />


                    You agree Mydr24, in its sole discretion and for any, including inter alia without limitation if you breach these Terms, may terminate your access to and use of the Platform, at any time. You agree that any termination of your access to the Platform and/ or suspension/ termination of your Account may be effected without prior notice, and in this respect Mydr24/ Platform shall not be liable to you for any such termination. Your right to use the Platform immediately ceases upon termination of your access/use of the Platform.
                    <br />
                    <br />
                    The provisions of these Terms shall continue to apply until terminated by either of the Party as set for below: (i) In case of User wanting to terminate these Terms, the User may do so by: (i) not accessing the Platform; or (ii)closing their Accounts.
                    <br />
                    <br />
                    We reserve the right to, at any time, and with or without notice, terminate these Terms against each of the Users, if there is
                    <br />
                    <br />
                    breach any of applicable law(s) or the provisions of these Terms or the terms of the Privacy Policy or any other terms, conditions, or policies that may be applicable to the User from time to time (or have acted in a manner that clearly shows that the User do not intend to, or are unable to, comply with the same); or
                    <br />
                    <br />
                    Platform is unable to verify or authenticate any information provided to the Platform by the User;
                    <br />
                    <br />
                    We believe, in its sole discretion, that the User’s actions may cause legal liability to Mydr24/ Platform, (or any of its affiliates, independent contractors, service providers, consultants, licensors, agents, and representatives) or are contrary to the interests of the Platform;
                    <br />
                    <br />
                    We are required to do so by law; or
                    <br />
                    <br />
                    if the User fails to provide (or after providing such consent, later revoke) the consents necessary or desirable for Mydr24 to provide the Services to the User;
                    <br />
                    <br />


                    LIABILITY
                    <br />
                    <br />


                    In no event shall we, or our officers, directors, employees, partners or suppliers be liable to you or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable or whether or not we have been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty, negligence or other tortious action, or any other claim arising out of or in connection with your use of or access of the Platform; purchase of the Products and availing of Consultation Service; any interaction, communication, dealing and transaction between the User and the Practitioner; and illegal/
                    <br />
                    <br />
                    unauthorized/ invalid prescription which has been uploaded by the User for purchasing the Products from the Platform.
                    <br />
                    <br />
                    The limitations and exclusions in this section apply to the maximum extent permitted by applicable law. Mydr24/ Platform accepts no liability for any loss or damage suffered due to the Users’ reliance on the product reviews posted by Users.
                    <br />
                    <br />
                    The User understands and agrees that (i) Mydr24 / Platform is not involved in providing healthcare or medical advice or diagnosis and, therefore. is not liable for interaction, communication, dealing and transaction between the User and the Practitioner; (ii) Mydr24/ Platform shall not be liable for any content posted, transmitted, exchanged or received by or on behalf of any User or another person on or through the Platform and any unauthorized access to or alteration of your transmission or data; (iii) Mydr24/ Platform is not liable for the ability, or lack of it, of the Practitioners to discharge his/her consultation services and obligations towards the User and any inconvenience, difficulty and/or harm caused to the User by such Practitioner.
                    <br />
                    <br />
                    Mydr24 and the Practitioner shall not be responsible for any inaccurate/ incorrect information provided by the User on the Platform.
                    <br />
                    <br />
                    User will be responsible for and releases Mydr24 from any and all liabilities, losses, claims and damages that may arise out of or in connection with the disclaimers as mentioned under these Terms and further agrees to hold harmless and indemnify Mydr24 in this regard.
                    <br />
                    <br />
                    In no event shall the total aggregate liability of Mydr24/ Platform to any User for all damages, losses, and causes of action (whether in contract or tort, including, but not limited to negligence, strict liability, product liability or otherwise) arising from these Terms or any your use of the Platform exceed an aggregate amount of INR 2500/- (Indian Rupees One Thousand only). We accept no liability for any errors or omissions on behalf of You.
                    <br />
                    <br />
                    In no event shall Mydr24 be liable for failure on the part of the Users or Third Party Advertisers to provide agreed services or to make himself/herself available at the appointed time, cancellation or rescheduling of appointments. In no event shall the Mydr24/ Platform be liable for any comments or feedback given by any of the Users in relation to the services provided by a Third Party Advertisers.
                    <br />
                    <br />
                    Mydr24/ Platform disclaims any liability in relation to the validity of the advice/ consultation provided by the Practitioner and the validity and legality of the e-prescription for dispensation of medicines. All liabilities arising out of any wrong diagnosis of medical condition by the Practitioners and/ or arising from the e-prescription will be of the concerned Practitioner.
                    <br />
                    <br />
                    The Users may share their previous medical history during interactions, communication, dealings and transaction with the Practitioners. The Users undertake
                    <br />
                    <br />
                    to share such information at their own risk. Mydr24/ Platform reserves the right to retain such information for the purpose of providing Services to the Users.
                    <br />
                    <br />
                    With respect to the Consultation Service, We will decide the Practitioner to whom the query should be directed based on the information shared by the User. However, in no event the Platform shall be held liable for the losses attributable to such decision making and in no event shall the Platform be liable for any Consultation provided and/or e-prescription issued by the Practitioner.


                    <br />
                    <br />
                    DISCLAIMER



                    <br />
                    <br />
                    THIS PLATFORM IS PROVIDED BY Mydr24 ON AN “AS IS” AND “AS AVAILABLE” BASIS AND Mydr24 MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THIS PLATFORM OR THE INFORMATION, CONTENT INCLUDED ON THIS PLATFORM. YOU EXPRESSLY AGREE THAT YOUR USE OF THIS PLATFORM IS AT YOUR SOLE RISK. Mydr24 RESERVES THE RIGHT TO WITHDRAW OR DELETE ANY INFORMATION FROM THIS PLATFORM AT ANY TIME IN ITS DISCRETION.
                    <br />
                    <br />
                    TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, Mydr24 DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED. Mydr24 DOES NOT WARRANT THAT THIS PLATFORM, ITS SERVERS, OR EMAIL/ OTHER COMMUNICATION SENT FROM THE Mydr24 ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. Mydr24 WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS PLATFORM, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE AND CONSEQUENTIAL DAMAGES.
                    <br />
                    <br />
                    Mydr24 DISCLAIMS RESPONSIBILITY FOR ANY HARM TO PERSONS RESULTING FROM ANY INSTRUCTIONS OR PRODUCTS REFERRED TO IN THE PLATFORM. WE DO NOT WARRANT THAT THE PLATFORM, OR ITS CONTENT WILL MEET YOUR REQUIREMENTS.
                    <br />
                    <br />
                    THE PLATFORM IS INTENDED FOR GENERAL PURPOSES ONLY AND IS NOT MEANT TO BE USED IN EMERGENCIES/SERIOUS ILLNESSES REQUIRING PHYSICAL CONSULTATION. FURTHER, IF THE PRACTITIONER ADJUDGES THAT A PHYSICAL EXAMINATION WOULD BE REQUIRED AND ADVISES IN-PERSON CONSULTATION, IT IS THE SOLE RESPONSIBILITY OF THE USER TO BOOK AN APPOINTMENT FOR PHYSICAL EXAMINATION AND IN-PERSON CONSULTATION WHETHER THE SAME IS WITH THE PRACTITIONER OR OTHERWISE. Mydr24 SHALL NOT BE LIABLE IN CASE OF ANY NEGLIGENCE ON THE PART OF THE USER IN ACTING ON THE SAME AND IF THE CONDITION OF THE USER SUBSEQUENTLY DETERIORATES.
                    <br />
                    <br />
                    YOU UNDERSTAND THAT THE PLATFORM ALLOWS YOU MAKE ONLINE APPOINTMENT/ CONSULTATION SESSION WITH THE PRACTITIONERS AND EVEN THOUGH Mydr24 TAKES ALL THE NECESSARY STEPS TO VERIFY
                    <br />
                    <br />
                    THE AUTHENTICITY OF THE PRACTITIONER, THE USER MUST UNDERSTAND AND AGREE THAT Mydr24 SHALL NOT BE LIABLE FOR ANY DEFICIENCIES INCLUDING BUT NOT LIMITED TO MISCONDUCT, INJURY CAUSED OR LACK OF KNOWLEDGE FROM THE END OF THE PRACTITIONERS.
                    <br />
                    <br />
                    ALL INTERACTION, COMMUNICATION, DEALING, OR TRANSACTION BETWEEN THE PRACTITIONER AND USERS IS A SEPARATE TRANSACTION WHICH INCLUDES WITHOUT ANY LIMITATION ALL WARRANTIES RELATED TO CONSULTATION AND AFTER CONSULTATION SERVICES. Mydr24 DOES NOT HAVE ANY CONTROL OVER SUCH INFORMATION AND PLAY NO DETERMINATIVE ROLE IN THE FINALIZATION OF THE SAME AND HENCE DO NOT STAND LIABLE FOR THE OUTCOMES OF SUCH COMMUNICATION. Mydr24/ PLATFORM DOES NOT ENDORSE ANY SPECIFIC PRACTITIONER ON THE PLATFORM NOR GUARANTEE ITS QUALITY AND VALUE. Mydr24 IS NOT A PARTY TO INTERACTIONS, COMMUNICATION, DEALINGS AND TRANSACTION BETWEEN THE PRACTITIONER AND USERS AND THEREFORE ASSUMES NO LIABILITY THAT ARISES FROM ANY SUCH ACTS OF THE PRACTITIONERS.
                    <br />
                    <br />
                    THE PLATFORM IS ONLY AN INTERMEDIARY AND CANNOT BE HELD LIABLE FOR ANY DISPUTE/CLAIM/DAMAGES THAT ARISE BETWEEN THE PRACTITIONERS AND THE USERS FOR WHATSOEVER REASON IT MAY BE.
                    <br />
                    <br />
                    Mydr24 SHALL NO LIABILITY FOR ANY LOSS OR DAMAGE SUFFERED DUE TO YOUR RELIANCE ON THE PRODUCT REVIEWS/ FEEDBACK AS POSTED ON THE PLATFORM.
                    <br />
                    <br />
                    Mydr24 HAS NO DOCTOR-PATIENT RELATIONSHIP WITH THE YOU/ USERS AND DOES NOT REPLACE THE RELATIONSHIP WITH YOUR PHYSICIAN AND/OR HEALTHCARE PROVIDER WHO ARE SEPARATE FROM THE PRACTITIONER LISTED ON THE PLATFORM.
                    <br />
                    <br />
                    THE OPINIONS, STATEMENTS, ANSWERS AND CONSULTATION PROVIDED BY THE PRACTITIONERS THROUGH THE PLATFORM ARE SOLELY THE INDIVIDUAL AND INDEPENDENT OPINIONS OF THE PRACTTIONER AND DO NOT IN ANY WAY REFLECT THE OPINIONS OF Mydr24.
                    <br />
                    <br />
                    PLATFORM HAS EXERTED REASONABLE EFFORTS TO ENSURE THAT ALL INFORMATION PUBLISHED ON THE WEBSITE/APP IS ACCURATE AT THE TIME OF POSTING; HOWEVER, THERE MAY BE ERRORS IN SUCH INFORMATION FOR WHICH WE SHALL HAVE NO LIABILITY. WE RESERVE THE RIGHT TO REMOVE OR ALTER ANY OF THE INFORMATION CONTAINED ON THE PLATFORM AT OUR SOLE DISCRETION.
                    <br />
                    <br />
                    THE PLATFORM CANNOT GUARANTEE THE ADEQUACY, CURRENCY OR COMPLETENESS OF THE PLATFORM CONTENT. Mydr24/ PLATFORM
                    <br />
                    <br />
                    DOES NOT WARRANT OR ENDORSE THE EFFECTIVENESS, QUALITY OR SAFETY OF THE PRODUCTS AVAILABLE ON THE PLATFORM.
                    <br />
                    <br />
                    WE MAY LET YOU VIEW OUR INFORMATION AND COMMUNICATE WITH US THROUGH SOCIAL MEDIA PLATFORMS SUCH AS FACEBOOK AND TWITTER. Mydr24/ PLATFORM EXPLICITLY DISCLAIMS ANY RESPONSIBILITY FOR THE TERMS OF USE AND PRIVACY POLICIES THAT GOVERN THESE THIRD-PARTY WEBSITES, WHICH ARE IN NO WAY ASSOCIATED WITH US.
                    <br />
                    <br />
                    NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, YOU ALONE SHALL BE LIABLE FOR YOUR INTERACTIONS, COMMUNICATION, DEALINGS AND TRANSACTION WITH PRACTITIONERS CONTACTED OR MANAGED THROUGH THE PLATFORM AND WE SHALL HAVE NO LIABILITY OR RESPONSIBILITY IN THIS REGARD. WE DO NOT GUARANTEE OR MAKE ANY REPRESENTATION WITH RESPECT TO THE CORRECTNESS, COMPLETENESS OR ACCURACY OF THE INFORMATION OR DETAIL PROVIDED BY SUCH CLIENT, PATIENT, USER, PRACTITIONER OR ANY THIRD PARTY THROUGH THE PLATFORM. THE SERVICES SHOULD NOT BE USED FOR EMERGENCY APPOINTMENT PURPOSES.
                    <br />
                    <br />
                    THE EXCHANGES BETWEEN THE PRACTITIONER AND THE PATIENT THROUGH THE CHAT WINDOW OR OVER TELEPHONE (AS THE CASE MAYBE) AND THE E-PRESCRIPTION WOULD BE ACCESSIBLE TO US FOR THE PURPOSES OF MONITORING THE QUALITY OF THE CONSULTATION.

                    <br />
                    <br />

                    SEVERABILITY

                    <br />
                    <br />

                    If for any reason, a court of competent jurisdiction finds any provision of these Terms, or portion thereof, to be unenforceable, that portion shall be enforced to the maximum extent permissible so as to give effect to the intent of the parties (the User and Mydr24 collectively) as reflected by that provision. The remainder of the Terms shall continue in full force and effect.


                    <br />
                    <br />
                    WAIVER


                    <br />
                    <br />
                    No provision of these Terms shall be deemed to be waived and no breach excused unless such waiver or consent shall be in writing and signed by the Mydr24. Any consent by Mydr24 to, or a waiver by Mydr24 of any breach committed by you, whether expressed or implied, shall not constitute consent to, waiver of, or excuse for any other different or subsequent breach.

                    <br />
                    <br />

                    GOVERNING LAW, JURISDICTION AND DISPUTE RESOLUTION

                    <br />
                    <br />

                    These Terms shall be governed by the laws of India. Subject to dispute resolution clause below, courts and tribunals of Faridabad have exclusive jurisdiction to settle any dispute arising out of or in connection with these Terms (including any disputes regarding the existence, validity or termination of these Terms).
                    <br />
                    <br />
                    The User agrees and understands that the transaction with the Practitioners are subject to the jurisdiction of Indian laws and that any claim, dispute or difference arising from it shall be subject to the jurisdiction provision as contained in the Terms and Conditions hereunder, at all times.
                    <br />
                    <br />
                    If any dispute, controversy or claim arises under, out of, or in relation to these Terms, including any dispute concerning the formation, construction, interpretation, or breach of these Terms, then such dispute shall at the first instance be attempted to be resolved through mutual good faith consultations. If the dispute is not resolved in this manner within forty-five (45) days of either party (you or we) sending a notice in this regard to the other party of such dispute, then the dispute shall be resolved by binding arbitration under the provisions of the Arbitration & Conciliation Act 1996, by a sole arbitrator in Mumbai. Such sole arbitrator shall be appointed by Mydr24.


                    <br />
                    <br />

                    OTHER TERMS


                    <br />
                    <br />
                    Other than that when expressly allowed, any use of our content and it being reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including “mirroring”) to any other computer, server, website or other medium for publication or distribution or for any commercial enterprise, without our express prior written consent is not allowed.
                    <br />
                    <br />
                    Please note that if You navigate away from the Platform to a third party website or application`, then You may be subject to and bound by alternative terms of use and privacy policy applicable to such third-party website or application.
                    <br />
                    <br />
                    Any complaints, abuse or concerns with regards to content and or comment or breach of these Terms shall be immediately informed to Rahul Krishnan (“Grievance Officer”) through email at care@Mydr24.com in with the electronic signature or in writing at the following address to:

                    [●]

                    The rights and obligations under the Terms which by their nature should survive will remain in full effect after termination or expiration of the Terms.
                    <br />
                    <br />
                    No partnership, joint venture or relationship of employee/employer or franchisor/franchisee arises between you and us by reason of the Terms.
                    <br />
                    <br />
                    In our discretion we may serve any notice or communication on you by mail. In the case of notices sent by mail, you will be deemed served 5 (five) business days after dispatch of the same.
                    <br />
                    <br />
                    As part of the registration process you agree to receive such marketing and promotional materials via mail, SMS, and/or any other mode of communication as we may deem appropriate to send you in connection with our Platform and Services. For further details relating to the same, please refer to our Privacy Policy.
                </p>
            </div>







        </>
    )
}
